-- MySQL Script generated by MySQL Workbench
-- Fri Oct 29 15:03:26 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema blog_marc_lassort
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blog_marc_lassort
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blog_marc_lassort` DEFAULT CHARACTER SET utf8 ;
USE `blog_marc_lassort` ;

-- -----------------------------------------------------
-- Table `blog_marc_lassort`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog_marc_lassort`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(14) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `role` TINYINT(4) NULL,
  `token` VARCHAR(255) NULL,
  `isActive` TINYINT(4) NOT NULL,
  `image` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog_marc_lassort`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog_marc_lassort`.`post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `blurb` VARCHAR(255) NOT NULL,
  `creation_date` DATETIME NOT NULL,
  `modif_date` DATETIME NOT NULL,
  `content` LONGTEXT NOT NULL,
  `author` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  `imageName` VARCHAR(255) NULL,
  `imageAlt` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_post_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `blog_marc_lassort`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog_marc_lassort`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog_marc_lassort`.`image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` LONGTEXT NOT NULL,
  `alt_text` VARCHAR(255) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `post_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_image_post1_idx` (`post_id` ASC),
  CONSTRAINT `fk_image_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `blog_marc_lassort`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog_marc_lassort`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog_marc_lassort`.`contact` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `author` VARCHAR(45) NOT NULL,
  `creation_date` DATETIME NOT NULL,
  `subject` VARCHAR(100) NOT NULL,
  `content` LONGTEXT NOT NULL,
  `email_address` VARCHAR(45) NOT NULL,
  `is_handled` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contact_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_contact_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `blog_marc_lassort`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog_marc_lassort`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blog_marc_lassort`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `content` LONGTEXT NOT NULL,
  `creation_date` DATETIME NOT NULL,
  `is_valid` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  `post_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_user1_idx` (`user_id` ASC),
  INDEX `fk_comment_post1_idx` (`post_id` ASC),
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `blog_marc_lassort`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `blog_marc_lassort`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
